public: true
type: "docs"
category: "reference and outreach"
tags:
  - "documentation"
  - "manual"
  - "markdown"
  - "github"
title: "Documentation Site Guide to Managing Content"
description: "A guide to adding and managing content in docs.rockarch.org."
pages:
  - ["About", "index"]
  - ["Add and Edit Content", "add-content"]
  - ["Using Markdown", "using-markdown"]
  - ["Using Github", "using-github"]
